resources:
- ../base
nameSuffix: -prod
patches:
- path: overlay.yaml
  target:
    kind: Deployment
    labelSelector: app=cicd-demo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: minghsu0107/cicd-demo
  newTag: main-b7d5a0f
- name: vincentfulin/ci-cd
  newTag: main-0bfa1db280d979ec1e9565d6390ef8b3b91db05b
