apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: cicd-demo-container
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "50m"
